package report

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/DannyAn/secguard-clang/internal/db"
	"github.com/DannyAn/secguard-clang/internal/planner"
)

type sarifReport struct {
	Schema  string     `json:"$schema"`
	Version string     `json:"version"`
	Runs    []sarifRun `json:"runs"`
}

type sarifRun struct {
	Tool    sarifTool     `json:"tool"`
	Results []sarifResult `json:"results"`
	// Properties.stage distinguishes the candidate-stage file written by `scan`
	// (unclassified pipeline leads) from the verdict-stage file regenerated by
	// `report --audit` (AI-classified findings). A consumer that treats the
	// first as final would report unclassified candidates as defects.
	Properties map[string]string `json:"properties,omitempty"`
}

type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}

type sarifDriver struct {
	Name    string      `json:"name"`
	Version string      `json:"version"`
	Rules   []sarifRule `json:"rules"`
}

type sarifRule struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type sarifResult struct {
	RuleID              string             `json:"ruleId"`
	Level               string             `json:"level"`
	Message             sarifMessage       `json:"message"`
	Locations           []sarifLocation    `json:"locations"`
	CodeFlows           []sarifCodeFlow    `json:"codeFlows,omitempty"`
	PartialFingerprints map[string]string  `json:"partialFingerprints,omitempty"`
	Fingerprints        map[string]string  `json:"fingerprints,omitempty"`
	Fixes               []sarifFix         `json:"fixes,omitempty"`
	Properties          map[string]string  `json:"properties,omitempty"`
	Suppressions        []sarifSuppression `json:"suppressions,omitempty"`
}

// sarifFix carries the AI's concrete fix strategy into the machine-readable
// report. description.text holds the fix (often a code snippet), so an
// IDE/CI consumer can surface "how to fix" alongside "what is wrong".
type sarifFix struct {
	Description sarifMessage `json:"description"`
}

type sarifCodeFlow struct {
	ThreadFlows []sarifThreadFlow `json:"threadFlows"`
}

type sarifThreadFlow struct {
	Locations []sarifThreadFlowLocation `json:"locations"`
}

type sarifThreadFlowLocation struct {
	Location sarifLocation `json:"location"`
}

type sarifSuppression struct {
	Kind          string `json:"kind"`
	Justification string `json:"justification,omitempty"`
}

type sarifMessage struct {
	Text string `json:"text"`
}

type sarifLocation struct {
	PhysicalLocation sarifPhysicalLocation `json:"physicalLocation"`
}

type sarifPhysicalLocation struct {
	ArtifactLocation sarifArtifactLocation `json:"artifactLocation"`
	Region           sarifRegion           `json:"region"`
	// ContextRegion carries the surrounding source window (SARIF 3.28.3.4), so
	// a viewer can show the finding in context without the source tree.
	ContextRegion *sarifRegion `json:"contextRegion,omitempty"`
}

type sarifArtifactLocation struct {
	URI string `json:"uri"`
}

type sarifRegion struct {
	StartLine int                   `json:"startLine"`
	EndLine   int                   `json:"endLine,omitempty"`
	Snippet   *sarifArtifactContent `json:"snippet,omitempty"`
}

type sarifArtifactContent struct {
	Text string `json:"text"`
}

// VulnToCWE returns the canonical CWE identifier for a vulnerability type,
// or "CWE-Other" if the type is not registered. The mapping is derived from
// planner.VulnTypeSpec.CWE — the single source of truth in planner/registry.go.
func VulnToCWE(vulnType string) string {
	cwe := planner.CWEForType(vulnType)
	if cwe == "" {
		return "CWE-Other"
	}
	return cwe
}

// writeCandidatesSarif emits the candidate-stage machine-readable report.
//
// Every result is SARIF level "note": these are converged-but-unclassified
// leads, and presenting an unclassified lead as an error is what the whole
// convergence pipeline exists to prevent. The pipeline's own prior travels in
// properties.suspicion_level, and the verdict-stage counterpart is result.sarif,
// written only after the AI classification is persisted.
func (o *ScanOutput) writeCandidatesSarif(packages []*planner.PlanResult) error {
	rules := []sarifRule{}
	results := []sarifResult{}

	rulesSeen := map[string]bool{}
	for _, pkg := range packages {
		cwe := planner.CWEForType(pkg.VulnerabilityType)
		if cwe == "" {
			cwe = "CWE-Other"
		}
		if !rulesSeen[cwe] {
			rulesSeen[cwe] = true
			rules = append(rules, sarifRule{
				ID:   cwe,
				Name: pkg.VulnerabilityType,
			})
		}

		for _, c := range pkg.Candidates {
			// Informational by construction — no candidate has been judged yet.
			level := "note"

			uri := c.Target.File
			if o.RootDir != "" && strings.HasPrefix(uri, o.RootDir) {
				uri = strings.TrimPrefix(uri, o.RootDir)
				uri = strings.TrimPrefix(uri, "/")
			}

			evidenceParts := []string{}
			for _, e := range c.Evidence {
				evidenceParts = append(evidenceParts, e.Detail)
			}

			result := sarifResult{
				RuleID: cwe,
				Level:  level,
				Message: sarifMessage{
					Text: fmt.Sprintf("%s in %s: %s", pkg.VulnerabilityType, c.Target.Function, strings.Join(evidenceParts, "; ")),
				},
				Locations: []sarifLocation{{
					PhysicalLocation: sarifPhysicalLocation{
						ArtifactLocation: sarifArtifactLocation{URI: uri},
						Region:           sarifRegion{StartLine: c.Target.Line},
					},
				}},
				PartialFingerprints: map[string]string{
					"primaryLocationLineHash": fmt.Sprintf("%s:%d", c.Target.Function, c.Target.Line),
				},
				Fingerprints: map[string]string{
					"ruleId:location": fmt.Sprintf("%s:%s:%d", cwe, c.Target.Function, c.Target.Line),
				},
				Properties: map[string]string{
					"stage": "candidate",
				},
			}
			if c.SuspicionLevel != "" {
				// The convergence prior, explicitly labelled as a prior — it is
				// an effort budget for the classifier, not a severity.
				result.Properties["suspicion_level"] = c.SuspicionLevel
			}

			if c.SourceLine > 0 && c.SourceLine != c.Target.Line {
				result.CodeFlows = []sarifCodeFlow{{
					ThreadFlows: []sarifThreadFlow{{
						Locations: []sarifThreadFlowLocation{
							{
								Location: sarifLocation{
									PhysicalLocation: sarifPhysicalLocation{
										ArtifactLocation: sarifArtifactLocation{URI: uri},
										Region:           sarifRegion{StartLine: c.SourceLine},
									},
								},
							},
							{
								Location: sarifLocation{
									PhysicalLocation: sarifPhysicalLocation{
										ArtifactLocation: sarifArtifactLocation{URI: uri},
										Region:           sarifRegion{StartLine: c.Target.Line},
									},
								},
							},
						},
					}},
				}}
			}

			results = append(results, result)
		}
	}

	report := sarifReport{
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Version: "2.1.0",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:    "secguard-clang",
					Version: ToolVersion,
					Rules:   rules,
				},
			},
			Results: results,
			Properties: map[string]string{
				"stage": "candidates",
				"note":  "Unclassified convergence-pipeline candidates at level \"note\" — NOT findings. The classified report is result.sarif, written by `secguard report --audit`.",
			},
		}},
	}

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	target := o.CandidatesSarifPath
	if target == "" {
		target = filepath.Join(o.ScanDir, CandidatesSarifFile)
	}
	return os.WriteFile(target, data, 0644)
}

// WriteSarifFromFindings regenerates the machine-readable report from the AI's
// persisted findings, so result.sarif carries the post-A5 verdict, the
// structured reasoning, and the concrete fix — not just the candidate-stage
// evidence. Dismissed (false-positive) findings are excluded; the actionable
// SARIF contains only confirmed + suspected.
func WriteSarifFromFindings(sarifPath, rootDir string, findings []*db.Finding) error {
	rules := []sarifRule{}
	results := []sarifResult{}
	rulesSeen := map[string]bool{}
	// The SARIF file lives inside the scan directory, so the project root (and
	// with it the source tree) is derivable without extra plumbing.
	sourceRoot := rootDir
	if sourceRoot == "" {
		sourceRoot = projectRootFromScanDir(filepath.Dir(sarifPath))
	}

	for _, f := range findings {
		status := f.EffectiveStatus()
		if status != "confirmed" && status != "suspected" {
			continue
		}

		cwe := strings.ToUpper(strings.TrimSpace(f.RuleID))
		if cwe == "" {
			cwe = "CWE-Other"
		}
		vulnType := planner.TypeForCWE(cwe)
		if vulnType == "" {
			vulnType = f.RuleID
		}
		if !rulesSeen[cwe] {
			rulesSeen[cwe] = true
			rules = append(rules, sarifRule{ID: cwe, Name: vulnType})
		}

		level := "warning"
		if status == "confirmed" {
			level = "error"
		}

		uri := f.FilePath
		if rootDir != "" && strings.HasPrefix(uri, rootDir) {
			uri = strings.TrimPrefix(uri, rootDir)
			uri = strings.TrimPrefix(uri, "/")
		}

		msg := f.Summary
		if msg == "" {
			msg = f.Reasoning
		}
		if msg == "" {
			msg = f.Evidence
		}
		if msg == "" {
			msg = f.FunctionName
		}

		// Embed the source region so the SARIF result is self-contained: a
		// viewer (or a reviewer reading raw JSON) sees the code, not just a
		// line number pointing into a tree they may not have.
		physical := sarifPhysicalLocation{
			ArtifactLocation: sarifArtifactLocation{URI: uri},
			Region:           sarifRegion{StartLine: f.LineNumber},
		}
		if ctx := readCodeContext(f.FilePath, f.LineNumber, ContextLines, sourceRoot); ctx != nil {
			if snippet := ctx.lineText(); snippet != "" {
				physical.Region.Snippet = &sarifArtifactContent{Text: snippet}
			}
			physical.ContextRegion = &sarifRegion{
				StartLine: ctx.StartLine,
				EndLine:   ctx.EndLine,
				Snippet:   &sarifArtifactContent{Text: ctx.text()},
			}
		}

		result := sarifResult{
			RuleID: cwe,
			Level:  level,
			Message: sarifMessage{
				Text: fmt.Sprintf("%s in %s: %s", vulnType, f.FunctionName, msg),
			},
			Locations: []sarifLocation{{PhysicalLocation: physical}},
			PartialFingerprints: map[string]string{
				"primaryLocationLineHash": fmt.Sprintf("%s:%d", f.FunctionName, f.LineNumber),
			},
			Fingerprints: map[string]string{
				"ruleId:location": fmt.Sprintf("%s:%s:%d", cwe, f.FunctionName, f.LineNumber),
			},
		}

		if f.Reasoning != "" || f.ExceptionCheck != "" {
			props := map[string]string{}
			if f.Reasoning != "" {
				props["reasoning"] = f.Reasoning
			}
			if f.ExceptionCheck != "" {
				props["exception_check"] = f.ExceptionCheck
			}
			result.Properties = props
		}
		if f.FixStrategy != "" {
			result.Fixes = []sarifFix{{Description: sarifMessage{Text: f.FixStrategy}}}
		}

		results = append(results, result)
	}

	report := sarifReport{
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Version: "2.1.0",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:    "secguard-clang",
					Version: ToolVersion,
					Rules:   rules,
				},
			},
			Results:    results,
			Properties: map[string]string{"stage": "findings", "note": "AI-classified verdicts (confirmed/suspected); dismissed findings excluded"},
		}},
	}

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(sarifPath, data, 0644)
}
