package report

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/DannyAn/secguard-clang/internal/db"
	"github.com/DannyAn/secguard-clang/internal/planner"
)

type sarifReport struct {
	Schema  string     `json:"$schema"`
	Version string     `json:"version"`
	Runs    []sarifRun `json:"runs"`
}

type sarifRun struct {
	Tool    sarifTool     `json:"tool"`
	Results []sarifResult `json:"results"`
	// Properties.stage distinguishes the candidate-stage file written by `scan`
	// (unclassified pipeline leads) from the verdict-stage file regenerated by
	// `report --audit` (AI-classified findings). A consumer that treats the
	// first as final would report unclassified candidates as defects.
	Properties map[string]string `json:"properties,omitempty"`
}

type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}

type sarifDriver struct {
	Name    string      `json:"name"`
	Version string      `json:"version"`
	Rules   []sarifRule `json:"rules"`
}

type sarifRule struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type sarifResult struct {
	RuleID              string             `json:"ruleId"`
	Level               string             `json:"level"`
	Message             sarifMessage       `json:"message"`
	Locations           []sarifLocation    `json:"locations"`
	CodeFlows           []sarifCodeFlow    `json:"codeFlows,omitempty"`
	PartialFingerprints map[string]string  `json:"partialFingerprints,omitempty"`
	Fingerprints        map[string]string  `json:"fingerprints,omitempty"`
	Fixes               []sarifFix         `json:"fixes,omitempty"`
	Properties          map[string]string  `json:"properties,omitempty"`
	Suppressions        []sarifSuppression `json:"suppressions,omitempty"`
}

// sarifFix carries the AI's concrete fix strategy into the machine-readable
// report. description.text holds the fix (often a code snippet), so an
// IDE/CI consumer can surface "how to fix" alongside "what is wrong".
type sarifFix struct {
	Description sarifMessage `json:"description"`
}

type sarifCodeFlow struct {
	ThreadFlows []sarifThreadFlow `json:"threadFlows"`
}

type sarifThreadFlow struct {
	Locations []sarifThreadFlowLocation `json:"locations"`
}

type sarifThreadFlowLocation struct {
	Location sarifLocation `json:"location"`
}

type sarifSuppression struct {
	Kind          string `json:"kind"`
	Justification string `json:"justification,omitempty"`
}

type sarifMessage struct {
	Text string `json:"text"`
}

type sarifLocation struct {
	PhysicalLocation sarifPhysicalLocation `json:"physicalLocation"`
}

type sarifPhysicalLocation struct {
	ArtifactLocation sarifArtifactLocation `json:"artifactLocation"`
	Region           sarifRegion           `json:"region"`
	// ContextRegion carries the surrounding source window (SARIF 3.28.3.4), so
	// a viewer can show the finding in context without the source tree.
	ContextRegion *sarifRegion `json:"contextRegion,omitempty"`
}

type sarifArtifactLocation struct {
	URI string `json:"uri"`
}

type sarifRegion struct {
	StartLine int                   `json:"startLine"`
	EndLine   int                   `json:"endLine,omitempty"`
	Snippet   *sarifArtifactContent `json:"snippet,omitempty"`
}

type sarifArtifactContent struct {
	Text string `json:"text"`
}

// sarifURI renders a filesystem path as the URI-reference a SARIF consumer can
// resolve. A bare absolute path is not a valid URI (it carries no scheme), so a
// viewer that resolves `artifactLocation.uri` as a relative reference reports
// "Unable to find <file>" instead of opening it. Absolute paths are therefore
// rendered as file:// URIs; relative paths are slash-normalised and left
// relative so the report can still travel with its source tree.
func sarifURI(path string) string {
	if path == "" {
		return ""
	}
	if !filepath.IsAbs(path) {
		return filepath.ToSlash(path)
	}
	u := url.URL{Scheme: "file", Path: filepath.ToSlash(path)}
	// A Windows drive-letter path (C:/...) must be rooted so the URI is
	// file:///C:/... rather than file://C:/... (which would parse "C:" as host).
	if len(u.Path) >= 2 && u.Path[1] == ':' {
		u.Path = "/" + u.Path
	}
	return u.String()
}

// VulnToCWE returns the canonical CWE identifier for a vulnerability type,
// or "CWE-Other" if the type is not registered. The mapping is derived from
// planner.VulnTypeSpec.CWE — the single source of truth in planner/registry.go.
func VulnToCWE(vulnType string) string {
	cwe := planner.CWEForType(vulnType)
	if cwe == "" {
		return "CWE-Other"
	}
	return cwe
}

// VulnToCWEForCategory returns the CWE identifier for a specific category within
// a vulnerability type, falling back to the type's canonical CWE when the
// category is not listed in CategoryCWEs. This is the per-category CWE resolver
// for vuln_types that cover multiple CWEs (e.g. injection's
// argument_injection→CWE-88, crlf_injection→CWE-93). Returns "CWE-Other" if
// the vuln_type is not registered.
func VulnToCWEForCategory(vulnType, category string) string {
	cwe := planner.CWEForCategory(vulnType, category)
	if cwe == "" {
		return "CWE-Other"
	}
	return cwe
}

// sarifLevel maps a finding's severity (impact) and status (evidence verdict)
// to the SARIF result level. severity drives the level; only a confirmed
// high/critical finding reads "error". A legacy "suspected" status is capped at
// "warning" (a lead, not a proven defect) — but the verdict is binary now, so a
// new finding never carries it.
func sarifLevel(severity, status string) string {
	switch normalizeSeverity(strings.ToLower(strings.TrimSpace(severity))) {
	case "critical", "high":
		if status == "confirmed" {
			return "error"
		}
		return "warning"
	case "medium":
		return "warning"
	case "low":
		return "note"
	default:
		// Unknown/empty severity (a hand-written finding): keep the old
		// status-only rule so the level never silently regresses to "note".
		if status == "confirmed" {
			return "error"
		}
		return "warning"
	}
}

// verdictMessageText builds the self-describing headline for one classified
// finding: severity, status, type, the variable in play, the function, and the
// file:line, with the AI summary/reasoning as the explanation. A reviewer can
// triage from this single line without opening the source — this replaces the
// old "<type> in <function>: <summary>" which left severity/status implicit.
func verdictMessageText(vulnType, function, file string, line int, variable, severity, status, summary string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "[%s · %s] %s", severity, status, vulnType)
	if variable != "" {
		fmt.Fprintf(&b, " on '%s'", variable)
	}
	if function != "" {
		fmt.Fprintf(&b, " in %s", function)
	}
	if file != "" {
		fmt.Fprintf(&b, " at %s:%d", shortFile(file), line)
	}
	if summary != "" {
		fmt.Fprintf(&b, " — %s", summary)
	}
	return b.String()
}

// writeCandidatesSarif emits the candidate-stage machine-readable report.
//
// Every result is SARIF level "note": these are converged-but-unclassified
// leads, and presenting an unclassified lead as an error is what the whole
// convergence pipeline exists to prevent. The pipeline's own prior travels in
// properties.suspicion_level, and the verdict-stage counterpart is result.sarif,
// written only after the AI classification is persisted.
func (o *ScanOutput) writeCandidatesSarif(packages []*planner.PlanResult) error {
	rules := []sarifRule{}
	results := []sarifResult{}

	rulesSeen := map[string]bool{}
	for _, pkg := range packages {
		for _, c := range pkg.Candidates {
			cwe := planner.CWEForCategory(pkg.VulnerabilityType, c.Category)
			if cwe == "" {
				cwe = "CWE-Other"
			}
			if !rulesSeen[cwe] {
				rulesSeen[cwe] = true
				rules = append(rules, sarifRule{
					ID:   cwe,
					Name: pkg.VulnerabilityType,
				})
			}

			// Informational by construction — no candidate has been judged yet.
			level := "note"

			// Keep the ABSOLUTE path so a viewer can double-click straight to
			// the file, rendered as a file:// URI — a bare absolute path is not
			// a valid URI, so a viewer resolves it as relative and reports
			// "Unable to find <file>".
			uri := sarifURI(c.Target.File)

			evidenceParts := []string{}
			for _, e := range c.Evidence {
				evidenceParts = append(evidenceParts, e.Detail)
			}

			candMsg := pkg.VulnerabilityType
			if c.Target.Variable != "" {
				candMsg += fmt.Sprintf(" on '%s'", c.Target.Variable)
			}
			candMsg += fmt.Sprintf(" in %s", c.Target.Function)
			if len(evidenceParts) > 0 {
				candMsg += ": " + strings.Join(evidenceParts, "; ")
			}

			result := sarifResult{
				RuleID: cwe,
				Level:  level,
				Message: sarifMessage{
					Text: candMsg,
				},
				Locations: []sarifLocation{{
					PhysicalLocation: sarifPhysicalLocation{
						ArtifactLocation: sarifArtifactLocation{URI: uri},
						Region:           sarifRegion{StartLine: c.Target.Line},
					},
				}},
				PartialFingerprints: map[string]string{
					"primaryLocationLineHash": fmt.Sprintf("%s:%d", c.Target.Function, c.Target.Line),
				},
				Fingerprints: map[string]string{
					"ruleId:location": fmt.Sprintf("%s:%s:%d:%s", cwe, c.Target.Function, c.Target.Line, c.Target.Variable),
				},
				Properties: map[string]string{
					"stage": "candidate",
				},
			}
			if c.SuspicionLevel != "" {
				// The convergence prior, explicitly labelled as a prior — it is
				// an effort budget for the classifier, not a severity.
				result.Properties["suspicion_level"] = c.SuspicionLevel
			}

			if c.SourceLine > 0 && c.SourceLine != c.Target.Line {
				result.CodeFlows = []sarifCodeFlow{{
					ThreadFlows: []sarifThreadFlow{{
						Locations: []sarifThreadFlowLocation{
							{
								Location: sarifLocation{
									PhysicalLocation: sarifPhysicalLocation{
										ArtifactLocation: sarifArtifactLocation{URI: uri},
										Region:           sarifRegion{StartLine: c.SourceLine},
									},
								},
							},
							{
								Location: sarifLocation{
									PhysicalLocation: sarifPhysicalLocation{
										ArtifactLocation: sarifArtifactLocation{URI: uri},
										Region:           sarifRegion{StartLine: c.Target.Line},
									},
								},
							},
						},
					}},
				}}
			}

			results = append(results, result)
		}
	}

	report := sarifReport{
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Version: "2.1.0",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:    "secguard-clang",
					Version: ToolVersion,
					Rules:   rules,
				},
			},
			Results: results,
			Properties: map[string]string{
				"stage": "candidates",
				"note":  "Unclassified convergence-pipeline candidates at level \"note\" — NOT findings. The classified report is result.sarif, written by `secguard report --audit`.",
			},
		}},
	}

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	target := o.CandidatesSarifPath
	if target == "" {
		target = filepath.Join(o.ScanDir, CandidatesSarifFile)
	}
	return os.WriteFile(target, data, 0644)
}

// WriteSarifFromFindings regenerates the machine-readable report from the AI's
// persisted findings, so result.sarif carries the post-A5 verdict, the
// structured reasoning, and the concrete fix — not just the candidate-stage
// evidence. Only CONFIRMED findings are included: the AI verdict is BINARY
// (confirmed vs dismissed), so an undecidable result is a dismissal, never a
// third "suspected" state.
func WriteSarifFromFindings(sarifPath, rootDir string, findings []*db.Finding) error {
	return writeSarifFromFindings(sarifPath, rootDir, findings, func(status string) bool {
		return status == "confirmed"
	}, "findings", "AI-classified CONFIRMED findings; dismissed findings excluded")
}

func writeSarifFromFindings(sarifPath, rootDir string, findings []*db.Finding, keep func(string) bool, stage, note string) error {
	rules := []sarifRule{}
	results := []sarifResult{}
	rulesSeen := map[string]bool{}
	// The SARIF file lives inside the scan directory, so the project root (and
	// with it the source tree) is derivable without extra plumbing.
	sourceRoot := rootDir
	if sourceRoot == "" {
		sourceRoot = projectRootFromScanDir(filepath.Dir(sarifPath))
	}

	for _, f := range findings {
		status := f.FinalStatus()
		if !keep(status) {
			continue
		}

		cwe := strings.ToUpper(strings.TrimSpace(f.RuleID))
		if cwe == "" {
			cwe = "CWE-Other"
		}
		vulnType := planner.TypeForCWE(cwe)
		if vulnType == "" {
			vulnType = f.RuleID
		} else if canonical := planner.CWEForType(vulnType); canonical != "" {
			// Normalize a legacy CWE (e.g. CWE-89 for injection) to the canonical
			// one (CWE-78) so one vulnerability type never yields two rules with
			// the same name.
			cwe = canonical
		}
		if !rulesSeen[cwe] {
			rulesSeen[cwe] = true
			rules = append(rules, sarifRule{ID: cwe, Name: vulnType})
		}

		level := sarifLevel(f.Severity, status)

		// Keep the ABSOLUTE path so a viewer can double-click to the file,
		// rendered as a file:// URI — a bare absolute path is not a valid URI,
		// so a viewer resolves it as relative and reports "Unable to find <file>".
		// A finding the agent wrote with a relative/truncated path is resolved
		// back to the indexed absolute path when possible.
		uri := f.FilePath
		if !filepath.IsAbs(uri) {
			if resolved := resolveSourcePath(uri, sourceRoot); resolved != "" {
				uri = resolved
			}
		}
		uri = sarifURI(uri)

		msg := f.Summary
		if msg == "" {
			msg = f.Reasoning
		}
		if msg == "" {
			msg = f.Evidence
		}
		sev := strings.ToLower(strings.TrimSpace(f.Severity))
		if sev == "" {
			sev = "info"
		}

		// Embed the source region so the SARIF result is self-contained: a
		// viewer (or a reviewer reading raw JSON) sees the code, not just a
		// line number pointing into a tree they may not have.
		physical := sarifPhysicalLocation{
			ArtifactLocation: sarifArtifactLocation{URI: uri},
			Region:           sarifRegion{StartLine: f.LineNumber},
		}
		if ctx := readCodeContext(f.FilePath, f.LineNumber, ContextLines, sourceRoot); ctx != nil {
			if snippet := ctx.lineText(); snippet != "" {
				physical.Region.Snippet = &sarifArtifactContent{Text: snippet}
			}
			physical.ContextRegion = &sarifRegion{
				StartLine: ctx.StartLine,
				EndLine:   ctx.EndLine,
				Snippet:   &sarifArtifactContent{Text: ctx.text()},
			}
		}

		result := sarifResult{
			RuleID: cwe,
			Level:  level,
			Message: sarifMessage{
				Text: verdictMessageText(vulnType, f.FunctionName, f.FilePath, f.LineNumber, f.Variable, sev, status, msg),
			},
			Locations: []sarifLocation{{PhysicalLocation: physical}},
			PartialFingerprints: map[string]string{
				"primaryLocationLineHash": fmt.Sprintf("%s:%d", f.FunctionName, f.LineNumber),
			},
			Fingerprints: map[string]string{
				"ruleId:location": fmt.Sprintf("%s:%s:%d:%s", cwe, f.FunctionName, f.LineNumber, f.Variable),
			},
		}

		// Every result carries its severity, verdict, confidence, and type as a
		// stable property bag so a SARIF viewer/CI policy can filter on them
		// (the level alone is a 3-value summary of the same two axes).
		result.Properties = map[string]string{
			"severity":   sev,
			"status":     status,
			"confidence": fmt.Sprintf("%.0f%%", f.Confidence*100),
			"vuln_type":  vulnType,
		}
		if f.Variable != "" {
			result.Properties["variable"] = f.Variable
		}
		if f.Reasoning != "" {
			result.Properties["reasoning"] = f.Reasoning
		}
		if f.ExceptionCheck != "" {
			result.Properties["exception_check"] = f.ExceptionCheck
		}
		if f.FixStrategy != "" {
			result.Fixes = []sarifFix{{Description: sarifMessage{Text: f.FixStrategy}}}
		}

		results = append(results, result)
	}

	report := sarifReport{
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Version: "2.1.0",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:    "secguard-clang",
					Version: ToolVersion,
					Rules:   rules,
				},
			},
			Results:    results,
			Properties: map[string]string{"stage": stage, "note": note},
		}},
	}

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(sarifPath, data, 0644)
}
